<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'db8EUf6JUqFF' );

/** MySQL database username */
define( 'DB_USER', 'g2Rj9yS72H' );

/** MySQL database password */
define( 'DB_PASSWORD', 'LPJihGKUwu' );

/** MySQL hostname */
define( 'DB_HOST', 'localhost' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';


/*
 * IMPORTANT
 * THIS IS NOT A STANDARD WP-CONFIG FILE
 * CHANGES SHOULD GO IN my-config.php
 * /var/www/vhosts/staging.greenmanwines.ie/httpdocs/my-config.php
 * DO NOT EDIT THIS FILE, IT WILL BE OVERRIDEN
 * https://www.34sp.com/kb/128/wordpress-hosting-file-structure
 *
 */

define('AUTH_KEY',         '218435eb8fa3e4d5c7a1f0837deca4c3');
define('SECURE_AUTH_KEY',  '04dc2adad41d42026ffc850be5317b8a');
define('LOGGED_IN_KEY',    '26a2edbf335d546498d4826e274acfcc');
define('NONCE_KEY',        '842229bc5b46f7a0ad4612fc8f390e33');
define('AUTH_SALT',        '73b58ad7097e59971420de2951deb46d');
define('SECURE_AUTH_SALT', '69b16dfd1a9baa2c5445647be35fb30d');
define('LOGGED_IN_SALT',   '8ac945d9475e0f9c45a69f33b630a029');
define('NONCE_SALT',       'c7a080cc07a97702f4ed038785b388b8');

define('WP_CACHE', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    define('FORCE_SSL_ADMIN', true);
    $_SERVER['HTTPS'] = 'on';
}
//Disable WordPress trying to update itself
define( 'WP_AUTO_UPDATE_CORE', false );

define('FS_METHOD', 'direct');
define( 'DISALLOW_FILE_EDIT', true );
define('WP_CONTENT_DIR', '/var/www/vhosts/staging.greenmanwines.ie/httpdocs/wp-content');
define('WP_CACHE_KEY_SALT', '29795bce0f2f08e25bc2275e29dc3153');

require_once('/var/www/vhosts/staging.greenmanwines.ie/httpdocs/my-config.php');

if(!defined('DISABLE_WP_CRON')) {
    define('DISABLE_WP_CRON', true);
}


/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) )
	define( 'ABSPATH', dirname( __FILE__ ) . '/' );

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
